/* Страница «dashboard» — подгружается по требованию из shell.js */
function dashboard(){const total=state.orders.length,newCount=state.orders.filter(o=>o.status==='NEW').length,problem=state.orders.filter(o=>['WAITING_STOCK','DELAYED','WAITING_VEHICLE','WAITING_PRODUCTION'].includes(o.status)).length,loading=state.orders.filter(o=>o.status==='LOADING').length;const shipped=state.orders.filter(o=>['LOADED','SHIPPED','COMPLETED'].includes(o.status)).reduce((a,o)=>a+o.actual,0);const todayOrders=state.orders.filter(o=>o.delivery==='18.09.2026').length;
state.products.forEach(ensureRes);
const DF=state.dashFactory||'Альянс',isAll=DF==='ALL';
const seg=`<div class="seg" role="tablist">${['Альянс','Агро','Гулистан','ALL'].map(k=>`<button class="${DF===k?'on':''}" onclick="setDashFactory('${k}')">${k==='ALL'?'Всего':k}</button>`).join('')}</div>`;
let stockCard;
if(isAll){
const factoryRows=state.products.map(p=>{const totalStock=Object.values(p.factories).reduce((a,b)=>a+b,0);const available=totalStock-p.reserved;return `<div class="factory-cell prod"><b title="${pTitle(p)}">${pTitle(p)}</b><small>${esc(p.sku)} · ${available.toFixed(0)} меш доступно</small></div>${FACTORIES.map(f=>`<div class="factory-cell ${f==='Гулистан'?'guli':''}"><b>${p.factories[f].toFixed(0)} меш</b><div class="stock-progress"><i style="width:${p.plan?Math.min(100,p.factories[f]/p.plan*100):0}%"></i></div></div>`).join('')}<div class="factory-cell"><b>${totalStock.toFixed(0)} меш</b></div><div class="factory-cell"><b>${p.reserved.toFixed(0)} меш</b></div>`}).join('');
const sS=state.products.reduce((a,p)=>a+FACTORIES.reduce((x,f)=>x+(p.factories[f]||0),0),0),sR=state.products.reduce((a,p)=>a+p.reserved,0);
stockCard=`<div class="glass section-card factory-stock"><div class="section-head"><div><h3>Остатки по товарам и заводам</h3><small>Все заводы · доступность = физический остаток − резерв</small></div>${seg}</div><div class="order-math" style="margin:0 0 12px"><div class="math"><small>Всего на заводах</small><b>${sS.toFixed(0)} меш</b></div><div class="math"><small>Всего в резерве</small><b>${sR.toFixed(0)} меш</b></div><div class="math"><small>Доступно</small><b>${Math.max(0,sS-sR).toFixed(0)} меш</b></div></div><div style="overflow-x:auto"><div class="factory-grid"><div class="factory-cell head">Товар</div><div class="factory-cell head">Альянс</div><div class="factory-cell head">Агро</div><div class="factory-cell head guli">Гулистан</div><div class="factory-cell head">Всего</div><div class="factory-cell head">Резерв</div>${factoryRows}</div></div></div>`;
}else{
const rows=state.products.map(p=>{const st=p.factories[DF]||0,rs=fRes(p,DF),av=fAvail(p,DF);return `<div class="factory-cell prod"><b title="${pTitle(p)}">${pTitle(p)}</b><small>${esc(p.sku)} · ${p.packKg} кг</small></div><div class="factory-cell ${DF==='Гулистан'?'guli':''}"><b>${st.toFixed(0)} меш</b><div class="stock-progress"><i style="width:${p.plan?Math.min(100,st/p.plan*100):0}%"></i></div></div><div class="factory-cell"><b>${rs.toFixed(0)} меш</b></div><div class="factory-cell"><b class="${av>0?'pos':'zero'}">${av.toFixed(0)} меш</b></div>`}).join('');
const sS=state.products.reduce((a,p)=>a+(p.factories[DF]||0),0),sR=state.products.reduce((a,p)=>a+fRes(p,DF),0),sA=state.products.reduce((a,p)=>a+fAvail(p,DF),0);
stockCard=`<div class="glass section-card factory-stock"><div class="section-head"><div><h3>Остатки · ${esc(DF)}</h3><small>Только ${esc(DF)} · доступно = остаток − резерв этого завода</small></div>${seg}</div><div class="order-math" style="margin:0 0 12px"><div class="math"><small>${esc(DF)} · всего на складе</small><b>${sS.toFixed(0)} меш</b></div><div class="math"><small>${esc(DF)} · всего резерв</small><b>${sR.toFixed(0)} меш</b></div><div class="math"><small>Доступно к заказу</small><b>${sA.toFixed(0)} меш</b></div></div><div style="overflow-x:auto"><div class="factory-grid f4"><div class="factory-cell head">Товар</div><div class="factory-cell head ${DF==='Гулистан'?'guli':''}">Остаток · ${esc(DF)}</div><div class="factory-cell head">Резерв</div><div class="factory-cell head">Доступно</div>${rows}</div></div></div>`;
}
const queue=state.orders.filter(o=>['READY','LOADING'].includes(o.status)).sort((a,b)=>a.slot.localeCompare(b.slot)).slice(0,5);
const urgent=state.orders.filter(o=>['WAITING_STOCK','DELAYED','LOADING'].includes(o.status)).slice(0,4);
const bars=[25,46,33,62,54,78,67,88,72,94,82,97];
const chartPts='0,152 48,138 96,145 144,116 192,126 240,83 288,97 336,72 384,90 432,52 480,63 528,35';
const planBars=state.products.slice(0,5).map(p=>`<div style=\"flex:1;text-align:center\"><i style=\"height:${Math.min(115,p.production/p.plan*115)}px;width:100%;display:block;background:var(--green);border-radius:8px 8px 3px 3px\"></i><small style=\"display:block;margin-top:6px;font-size:8px;color:var(--muted)\">${pTitle(p)}</small></div>`).join('');
const factoryTotal={ 'Альянс':0,'Агро':0,'Гулистан':0 };state.products.forEach(p=>Object.keys(factoryTotal).forEach(f=>factoryTotal[f]+=p.factories[f]||0));
const factoryMax=Math.max(1,...Object.values(factoryTotal));
const factoryBars=Object.entries(factoryTotal).map(([f,v])=>`<div style=\"margin-top:14px\"><div style=\"display:flex;justify-content:space-between;font-size:9px\"><b>${f}</b><span>${v.toFixed(0)} меш</span></div><div class=\"progress-track\" style=\"margin-top:6px\"><i style=\"width:${v/factoryMax*100}%\"></i></div></div>`).join('');
document.getElementById('dashboard').innerHTML=`${pageHead('Добрый вечер, Махмудали','Смена День · 18 сентября 2026 · Контроль заказов от Telegram до фактической погрузки','<button class="btn primary" onclick="newOrder()">＋ Новый заказ</button><button class="btn" onclick="openCommand()">⌘ Command Center</button>')}
<div class="metrics"><div class="glass metric"><div class="label">Заказов сегодня</div><div class="num">${todayOrders}</div><div class="sub">${newCount} новых · ${problem} требуют внимания</div><div class="spark">LIVE</div></div><div class="glass metric"><div class="label">Ожидают погрузки</div><div class="num">${state.orders.filter(o=>o.status==='READY').length}</div><div class="sub">${loading} машин сейчас в погрузке</div></div><div class="glass metric"><div class="label">Отгружено сегодня</div><div class="num">${shipped.toFixed(1)} меш</div><div class="sub">LOADED / SHIPPED / COMPLETED</div></div><div class="glass metric"><div class="label">Проблемные</div><div class="num">${problem}</div><div class="sub">остаток · задержка · машина</div></div></div>
${stockCard}
<div class="bento"><div class="chart-dark"><div class="chart-title"><b>Поток отгрузок · последние 12 часов</b><span>LIVE OPERATION</span></div><svg class="chart" viewBox="0 0 540 210" preserveAspectRatio="none"><defs><linearGradient id="areaFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#a9ba9d" stop-opacity=".30"/><stop offset="1" stop-color="#a9ba9d" stop-opacity=".02"/></linearGradient></defs><line class="chart-grid" x1="0" y1="50" x2="540" y2="50"/><line class="chart-grid" x1="0" y1="100" x2="540" y2="100"/><line class="chart-grid" x1="0" y1="150" x2="540" y2="150"/><polyline class="chart-area" points="${chartPts} 528,180 0,180"/><polyline class="chart-line" points="${chartPts}"/><circle class="chart-points" cx="528" cy="35" r="4"/><text class="chart-label" x="4" y="202">07:00</text><text class="chart-label" x="190" y="202">11:00</text><text class="chart-label" x="374" y="202">15:00</text><text class="chart-label" x="500" y="202">18:00</text></svg></div>
<div class="mini-grid"><div class="glass mini-stat"><div class="label">Telegram → Confirmed</div><div class="num">8 мин</div><div class="note">среднее время ответа</div><div class="bar-cluster">${bars.slice(0,8).map(v=>`<i style="height:${v/1.6}px"></i>`).join('')}</div></div><div class="glass mini-stat"><div class="label">Loading duration</div><div class="num">42 мин</div><div class="note">средняя погрузка</div><div class="bar-cluster">${bars.slice(3,11).map(v=>`<i style="height:${v/1.9}px"></i>`).join('')}</div></div><div class="glass mini-stat"><div class="label">On-time loading</div><div class="num">94%</div><div class="note">слоты без задержки</div><div class="stock-progress" style="margin-top:18px;height:9px"><i style="width:94%"></i></div></div><div class="glass mini-stat"><div class="label">Queue wait</div><div class="num">18 мин</div><div class="note">среднее ожидание машины</div><div class="stock-progress" style="margin-top:18px;height:9px"><i style="width:72%"></i></div></div></div></div>
<div class="operations"><div class="glass section-card"><div class="section-head"><h3>Что требует внимания</h3><small>DO NOW / PROBLEM</small></div><div class="list">${urgent.map(o=>{const p=productBy(o.productId);const txt=o.status==='WAITING_STOCK'?`дефицит ${Math.max(0,o.qty-(Object.values(p.factories).reduce((a,b)=>a+b,0)-p.reserved)).toFixed(1)} меш`:o.status==='LOADING'?`машина в погрузке · ${o.actual.toFixed(1)} / ${o.qty} меш`:o.status==='DELAYED'?`слот ${o.slot} · машина ожидает подтверждения`:'требуется действие';return `<div class="list-row"><div class="avatar-mini">${ico(o.status==='LOADING'?'truck':'audit',20)}</div><div class="body"><b>Заказ #${esc(o.id.split('-').pop())} · ${esc(txt)}</b><small>${pTitle(p)} · ${u(o.qty,p)} · ${esc(o.client)}</small></div>${statusBadge(o.status)}<button class="btn mini" onclick="openOrder('${o.id}')">${o.status==='LOADING'?'Контроль':'Открыть'}</button></div>`}).join('')}</div></div>
<div class="glass section-card queue-card"><div class="section-head"><h3>Очередь погрузки</h3><small>Сегодня</small></div>${queue.map(o=>{const v=vehicleBy(o.vehicleId);const p=productBy(o.productId);return `<div class="queue-row"><div class="queue-time">${esc(o.slot)}</div><div><b>${esc(v?.plate||'Самовывоз')} · ${esc(o.client)}</b><small>${pTitle(p)} · ${u(o.qty,p)} · ${esc(v?.driver||'клиент')}</small></div>${statusBadge(o.status)}<button class="arrow-btn" onclick="openOrder('${o.id}')">→</button></div>`}).join('')}</div></div><div class="extra-charts"><div class="glass chart-card"><h4>Производство · план / факт</h4><small>Сегодня, мешки</small><div class="bars" style="height:150px;margin-top:10px">${planBars}</div><div style="display:flex;justify-content:space-between;margin-top:7px;font-size:8px;color:var(--muted)"><span>Факт</span><span>План</span></div></div><div class="glass chart-card"><h4>Остаток по заводам</h4><small>Физический запас</small>${factoryBars}<div class="donut-wrap" style="margin-top:16px"><div class="donut" style="width:78px;height:78px;background:conic-gradient(var(--green) 0 52%,#b7c1ae 52% 78%,#ddd6b7 78% 100%)"><strong style="font-size:13px">${Math.round((factoryTotal.Альянс+factoryTotal.Агро+factoryTotal.Гулистан)/3)}</strong></div><div class="muted" style="font-size:9px">Средний запас на завод</div></div></div><div class="glass chart-card"><h4>Структура текущей смены</h4><small>Заказы по стадиям</small><div class="donut-wrap" style="margin-top:13px"><div class="donut"><strong>${todayOrders}</strong></div><div class="legend"><div><b>READY</b><span>${state.orders.filter(o=>o.status==='READY').length}</span></div><div><b>LOADING</b><span>${loading}</span></div><div><b>PROBLEM</b><span>${problem}</span></div><div><b>COMPLETED</b><span>${state.orders.filter(o=>o.status==='COMPLETED').length}</span></div></div></div><div class="progress-track" style="margin-top:15px"><i style="width:${todayOrders?state.orders.filter(o=>o.status==='COMPLETED').length/todayOrders*100:0}%"></i></div></div></div>`}

function setDashFactory(k){state.dashFactory=k;save();dashboard()}
